### ISSUE TITLE
When searching for subdomains, I'd like the input to be used as is

### ISSUE THREAD

**Issue by dee-see** [Cgboal/SonarSearch#19]
Hello!

When hitting the `/subdomains/{domain}` endpoint, if `domain` is `abc.domain.com`, the subdomain search will run for `domain.com` because of https://github.com/Cgboal/SonarSearch/blob/3135da3283dcb9c463aca01a0e3924be9c1f499f/crobat-server/server.go#L99

I wish it ran on `abc.domain.com` as provided. For example if I want `sports.yahoo.com` subdomains, searching for `yahoo.com` instead provides many uninteresting results and makes the execution much longer.

I'd be happy to contribute this feature but I'm wondering how you'd prefer to see this implemented. A new route? Or a query parameter on the existing route?

Thanks!

**Comment by Cgboal** [comment]
Basically this is due to the way the data is indexed in the database. I
dont think we'd manage to index it properly with all the various levels of
sub-sub domains, however, should be simple enough to filter the results
once they've been extracted from the database. Will implement this sometime
this week.

**Comment by Cgboal** [comment]
This is done now, give it a shot.

**Comment by Cgboal** [comment]
Ah actually it's not perfect, 1 sec

**Comment by Cgboal** [comment]
Okay now it should work great

**Comment by dee-see** [comment]
Awesome, thanks!
